version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: filament-php
    container_name: filament-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    networks:
      - filament

  nginx:
    image: nginx:alpine
    container_name: filament-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - filament

  db:
    image: mysql:8.0
    container_name: filament-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: filament
      MYSQL_USER: filament
      MYSQL_PASSWORD: filament
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - filament

networks:
  filament:

volumes:
  db_data:
